name: rooting-droid Docker Image CI

on: [push]
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: timwm/rooting-droid@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: echo "The [ ${{ env.LARGE_SECRET_PASSPHRASE }} ... ${{ secrets.DOCKER_HUB_TOKEN }}] time was ${{ steps.hello.outputs.time }}"
  build:
    runs-on: ubuntu-latest
    name: Build the docker image
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io

        #     *** STEP 1 ***
        #  docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        #  docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA


        #      **** STEP 2 ****
        #docker [image, container] ls --all
        #
        docker create -t ubuntu bash --name xvx --cpus 16 --cpuset-cpu 0-14 --label my-label --workdir / # -m "commit ..36" #44
        docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        #> Digest: sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573c93cb605a0e2fb
        #> Status: Downloaded newer image for ubuntu:latest
        #> 43dd45856f7cba5642622e971ee62eb62408f58138c5778f47ac600d28fc20d4
        #
        docker container ls -a
        #docker exec -it 095timw013579111317/github_repo:a3f77e288dd766121b401a5354b3e86fe04e3e40 /bin/bash
        #docker pull 095timw013579111317/github_repo:a3f77e288dd766121b401a5354b3e86fe04e3e40
