on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: timwm/rooting-droid@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: echo "The [ ${{ env.LARGE_SECRET_PASSPHRASE }} ooo ${{ secrets.DOCKER_HUB_TOKEN }} ooo ${{ secrets.docker.DOCKER_HUB_TOKEN }} ] time was ${{ steps.hello.outputs.time }}"
